const randint = require("./randint.js");
const resources = require("./resources");

const array = [
  {
    name: "cookie",
    description: " **Cookie**\nA tasty snack.",
    aliases: ["cookies"],
    emote: "🍪",
    upgradeAble: false,
    canUse: true,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 10,
    price: 50,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {
      const cookieRandom = [
        "You ate a cookie as you was feeling hungry.",
        "You choked on a cookie and almost died.",
        "The cookie tasted great.",
      ];
      const yes = cookieRandom[Math.floor(Math.random() * cookieRandom.length)];
      message.channel.send(`${yes}`);
    },
  },
  {
    name: "padlock",
    description: ` **Padlock**\nHelps you stop those pesky robbers.`,
    emote: "🔒",
    aliases: ["padlocks"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 2000,
    price: 10000,
    keep: true,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "fishingrod",
    description: " **Fishing Rod**\nLets you catch fish.",
    emote: "🎣",
    aliases: ["fishingrods", "rod", "fishing"],
    upgradeAble: true,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 15000,
    keep: true,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "common",
    description: " **Common Fish** \nSell common fish to make money.",
    emote: "🐟",
    aliases: ["commonfish", "fish"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 250,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "uncommon",
    description: "**Uncommon Fish** \nsell uncommon fish to make money.",
    emote: "🐠",
    aliases: ["uncommonfish", "ufish"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "rare",
    description: "**Rare Fish** \nSell rare fish to make money.",
    emote: "🦑",
    aliases: ["rarefish", "rfish"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 1250,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "veryrare",
    description: "**Very Rare Fish** \nSell very rare fish to make money.",
    emote: "🐡",
    aliases: ["veryrarefish", "vrfish"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 750,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "legendary",
    description: `**Legendary Fish** \nSell legendary fish to make money.`,
    emote: "🦈",
    aliases: ["legendaryfish", "lfish"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 2000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "junk",
    description: `**Junk**\nSell junk to make money.`,
    emote: "🗑️",
    aliases: ["useless", "garbage"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 100,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "banknote",
    description: `**Bank Note**\nIncreases your bank's capacity.`,
    emote: "📜",
    aliases: ["banknotes", "note", "bank"],
    upgradeAble: false,
    canUse: true,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 6667,
    unsellable: true,
    price: 20000,
    keep: false,
    autosell: false,
    run: async (bot, message, number, util) => {
      let user = await bot.economy.getConfig(message.member);

      let totalInc = 20000 * number;

      user.bankSpace += totalInc;
      await user.save();

      message.reply({
        msg: message,
        title: `You used ${number} ${number > 1 ? "banknotes" : "banknote"}!`,
        description: `Your bank space was increased by **${totalInc.toLocaleString()}** credits.
            \nYou can now store a total of **${user.bankSpace.toLocaleString()}** credits!`,
      });
    },
  },
  {
    name: "rifle",
    description: ` **Rifle**\nLets you hunt animals.`,
    emote: "<:rifle:941712531637039204>",
    aliases: ["rifles", "gun", "rifle"],
    upgradeAble: true,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 22500,
    keep: true,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "chicken",
    description:
      " **Chicken**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🐔",
    aliases: ["chickens", "chick"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "duck",
    description:
      "**Duck**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🦆",
    aliases: ["ducks", "duck"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 750,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "rabbit",
    description:
      "**Rabbit**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🐇",
    aliases: ["rabbits", "rabbit"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 1250,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "fox",
    description:
      "**Fox**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🦊",
    aliases: ["foxes", "fox"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 2250,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "pig",
    description:
      "**Pig**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🐷",
    aliases: ["pigs", "pig"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 2500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "deer",
    description:
      "**Deer**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🦌",
    aliases: ["deers", "deer"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 3500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "boar",
    description:
      "**Boar**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🐗",
    aliases: ["boars", "boar"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 4000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "cow",
    description:
      "**Cow**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🐮",
    aliases: ["cows", "cow"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 4500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "bear",
    description:
      "**Bear**\nAn animal which is hunted, and sold to earn credits.",
    emote: "🐻",
    aliases: ["bears", "bear"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 5000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "pickaxe",
    description: `**Pickaxe**\nLets you mine gems.`,
    emote: "⛏️",
    aliases: ["pickaxes", "pickaxe"],
    upgradeAble: true,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 30000,
    keep: true,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "gem",
    description: "**Gem**\nSell gems to make money.",
    emote: "<:gem-1:941713165203410954> ",
    aliases: ["gems", "gem"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 1000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "diamond",
    description: `**Diamond**\nA gem obtained by mining, and sold to earn credits.`,
    emote: "💎",
    aliases: ["diamonds", "diamond"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 2000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "ruby",
    description: `**Ruby**\nA gem obtained by mining, and sold to earn credits.`,
    emote: "<:ruby:941713578464006144>",
    aliases: ["rubies", "ruby"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 2250,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "jade",
    description: `**Jade**\nA gem obtained by mining, and sold to earn credits.`,
    emote: "<:jade:941713818420129862>",
    aliases: ["jades", "jade"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 3000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "amethyst",
    description: `**Amethyst**\nA gem obtained by mining, and sold to earn credits.`,
    emote: "<:amethyst:941714172511682620>",
    aliases: ["amethysts", "amethyst"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 3500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "precious",
    description: `**Precious**\nA gem obtained by mining, and sold to earn credits.`,
    emote: "<:precious:941714445862858782>",
    aliases: ["preciouss", "precious"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 5000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "axe",
    description: `**Axe**\nLets you cut trees down.`,
    emote: "🪓",
    aliases: ["axes", "axe"],
    upgradeAble: true,
    canUse: true,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 3000,
    price: 20000,
    keep: true,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "oak",
    description: `**Oak**\nA log of wood obtained by lumbering, and sold to earn credits.`,
    emote: "🌲",
    aliases: ["oaks", "oak"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 1500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "palm",
    description: `**palm**\nA log of wood obtained by lumbering, and sold to earn credits.`,
    emote: "🌴",
    aliases: ["palms", "palm"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 1750,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "fir",
    description: `**Fir**\nA log of wood obtained by lumbering, and sold to earn credits.`,
    emote: "🎄",
    aliases: ["firs", "fir"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 2000,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "ebony",
    description: `**Ebony**\nA log of wood obtained by lumbering, and sold to earn credits.`,
    emote: "🌳",
    aliases: ["ebonys", "ebony"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 2750,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "maple",
    description: `🍁 **Maple**\nA log of wood obtained by lumbering, and sold to earn credits.`,
    emote: "🍁",
    aliases: ["maples", "maple"],
    upgradeAble: false,
    canUse: false,
    canBuy: false,
    displayOnShop: false,
    sellAmount: 4500,
    price: 0,
    keep: true,
    autosell: true,
    run: async (bot, message, args) => {},
  },
  {
    name: "luckyclover",
    description: `**Lucky Clover**\nIncreases your chances of a sucessful robbery.`,
    emote: "🍀",
    aliases: ["luckys", "luckyclovers", "luckyclover"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 4000,
    price: 10000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "diamondcoin",
    description: `**Aeona Diamond Coin** \n Makes chance of winning +coinflip to 75%`,
    emote: "<:diamond_coin:941716739547361350>",
    aliases: ["diamondcoins", "diamondcoin"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 50000000,
    price: 100000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "goldcoin",
    description: `**Aeona Gold Coin** \n Makes chance of winning +coinflip to 50%`,
    emote: "🪙",
    aliases: ["goldcoins", "goldcoin"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 25000000,
    price: 50000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "silvercoin",
    description: `**Aeona Silver Coin**\n Makes chance of winning +coinflip to 35%`,
    emote: "<:silver_coin:941716938642587708>",
    aliases: ["silvercoins", "silvercoin"],
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 7500000,
    price: 15000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "bronzecoin",
    description: `**Aeona Bronze Coin** \n Makes chance of winning +coinflip to 25%`,
    emote: "<:bronze_coin:941717128044761119>",
    aliases: ["bronzecoins", "bronzecoin"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 2500000,
    price: 5000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "trophy",
    description: `**Aeona Trophy** \n Increases +gamble limit from 10 million to 50 million`,
    emote: "🏆",
    aliases: ["trophies", "trophy"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 50000000,
    price: 100000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "cxldtrophy",
    description: `**Cxld Trophy** \n Increases +gamble limit from 50 million to 100 million`,
    emote: "🥉",
    aliases: ["cxldtrophies", "cxldtrophy"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 5000000000,
    price: 10000000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "sentienttrophy",
    description: `**Sentient Trophy** \n Increases +gamble limit from 100 million to 900 million`,
    emote: "🥈",
    aliases: ["sentienttrophies", "sentienttrophy"],
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 500000000000,
    price: 1000000000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "allegianttrophy",
    description: `**Allegiant Trophy** \n Increases +gamble limit from 900 million to 100 billion`,
    emote: "🥇",
    aliases: ["allegianttrophies", "allegianttrophy"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 50000000000000,
    price: 100000000000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "watchertrophy",
    description: `**Watcher Trophy** \n Increases +gamble limit from 100 billion to 1 trillion`,
    emote: "🕵️",
    aliases: ["watchertrophies", "watchertrophy"],
    upgradeAble: false,
    canUse: false,
    canBuy: true,
    displayOnShop: true,
    unsellable: true,
    sellAmount: 5000000000000000000,
    price: 10000000000000000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
  {
    name: "luck",
    description: ` **Bottle O' Luck**\nIncreases your chances of winning a gamble.`,
    emote: "🍀",
    aliases: ["lucks", "luck", "bottle"],
    upgradeAble: false,
    canUse: false,
    // canBuy: true,
    // displayOnShop: true,
    canBuy: true,
    displayOnShop: true,
    sellAmount: 500000,
    price: 10000000,
    keep: false,
    autosell: false,
    run: async (bot, message, args) => {},
  },
];

module.exports = array;
